import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';
import { getTsVectorColumnExpressionFromFields } from 'src/engine/workspace-manager/utils/get-ts-vector-column-expression.util';
import { SEARCH_FIELDS_FOR_OPPORTUNITY } from 'src/modules/opportunity/standard-objects/opportunity.workspace-entity';

export const buildOpportunityStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'opportunity', FieldMetadataType>,
  'context'
>): Record<AllStandardObjectFieldName<'opportunity'>, FlatFieldMetadata> => ({
  // Base fields from BaseWorkspaceEntity
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'now',
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'now',
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIReadOnly: true,
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Opportunity-specific fields
  name: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'name',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Name`),
      description: i18nLabel(msg`The opportunity name`),
      icon: 'IconTargetArrow',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  amount: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'amount',
      type: FieldMetadataType.CURRENCY,
      label: i18nLabel(msg`Amount`),
      description: i18nLabel(msg`Opportunity amount`),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  closeDate: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'closeDate',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Close date`),
      description: i18nLabel(msg`Opportunity close date`),
      icon: 'IconCalendarEvent',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  stage: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'stage',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Stage`),
      description: i18nLabel(msg`Opportunity stage`),
      icon: 'IconProgressCheck',
      isNullable: false,
      defaultValue: "'A_ENVOYER_EN_MPR'",
      options: [
        {
          id: '30303030-0001-4afd-9c39-d2063097587a',
          value: 'A_ENVOYER_EN_MPR',
          label: i18nLabel(msg`A envoyer en MPR`),
          position: 0,
          color: 'sky',
        },
        {
          id: '30303030-0002-4afd-9c39-d2063097587a',
          value: 'DOSSIER_DEPOSE',
          label: i18nLabel(msg`Dossier déposé`),
          position: 1,
          color: 'blue',
        },
        {
          id: '30303030-0003-4afd-9c39-d2063097587a',
          value: 'VISITE_TECHNIQUE',
          label: i18nLabel(msg`Visite technique`),
          position: 2,
          color: 'purple',
        },
        {
          id: '30303030-0004-4afd-9c39-d2063097587a',
          value: 'DEVIS',
          label: i18nLabel(msg`Devis`),
          position: 3,
          color: 'turquoise',
        },
        {
          id: '30303030-0005-4afd-9c39-d2063097587a',
          value: 'INSTALLATION_PLANIFIE',
          label: i18nLabel(msg`Installation planifié`),
          position: 4,
          color: 'orange',
        },
        {
          id: '30303030-0006-4afd-9c39-d2063097587a',
          value: 'INSTALLATION_EN_COURS',
          label: i18nLabel(msg`Installation en cours`),
          position: 5,
          color: 'yellow',
        },
        {
          id: '30303030-0007-4afd-9c39-d2063097587a',
          value: 'INSTALLATION_TERMINE',
          label: i18nLabel(msg`Installation terminé`),
          position: 6,
          color: 'green',
        },
        {
          id: '30303030-0008-4afd-9c39-d2063097587a',
          value: 'COMMISSION_PAYE',
          label: i18nLabel(msg`Commission payé`),
          position: 7,
          color: 'green',
        },
        {
          id: '30303030-0009-4afd-9c39-d2063097587a',
          value: 'DOSSIER_BLOQUE',
          label: i18nLabel(msg`Dossier bloqué`),
          position: 8,
          color: 'red',
        },
        {
          id: '30303030-0010-4afd-9c39-d2063097587a',
          value: 'DOSSIER_ANNULE',
          label: i18nLabel(msg`Dossier annulé`),
          position: 9,
          color: 'gray',
        },
        {
          id: '20202020-8e01-4afd-9c39-d2063097587a',
          value: 'NEW',
          label: i18nLabel(msg`New`),
          position: 50,
          color: 'red',
        },
        {
          id: '20202020-e685-4671-ac32-26d304dacb6e',
          value: 'SCREENING',
          label: i18nLabel(msg`Screening`),
          position: 51,
          color: 'purple',
        },
        {
          id: '20202020-dde9-4acc-b5ca-f6531a8ecb4a',
          value: 'MEETING',
          label: i18nLabel(msg`Meeting`),
          position: 52,
          color: 'sky',
        },
        {
          id: '20202020-696e-4f6b-91bc-f413e9b2f654',
          value: 'PROPOSAL',
          label: i18nLabel(msg`Proposal`),
          position: 53,
          color: 'turquoise',
        },
        {
          id: '20202020-0bb5-4a6f-a8b2-774bbad21104',
          value: 'CUSTOMER',
          label: i18nLabel(msg`Customer`),
          position: 54,
          color: 'yellow',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: i18nLabel(msg`Position`),
      description: i18nLabel(msg`Opportunity record position`),
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Created by`),
      description: i18nLabel(msg`The creator of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIReadOnly: true,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Updated by`),
      description: i18nLabel(
        msg`The workspace member who last updated the record`,
      ),
      icon: 'IconUserCircle',
      isSystem: true,
      isUIReadOnly: true,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: i18nLabel(msg`Search vector`),
      description: i18nLabel(msg`Field used for full-text search`),
      icon: 'IconUser',
      isSystem: true,
      isNullable: true,
      settings: {
        generatedType: 'STORED',
        asExpression: getTsVectorColumnExpressionFromFields(
          SEARCH_FIELDS_FOR_OPPORTUNITY,
        ),
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Relation fields
  pointOfContact: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'pointOfContact',
      label: i18nLabel(msg`Point of Contact`),
      description: i18nLabel(msg`Opportunity point of contact`),
      icon: 'IconUser',
      isNullable: true,
      targetObjectName: 'person',
      targetFieldName: 'pointOfContactForOpportunities',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'pointOfContactId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  company: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'company',
      label: i18nLabel(msg`Company`),
      description: i18nLabel(msg`Opportunity company`),
      icon: 'IconBuildingSkyscraper',
      isNullable: true,
      targetObjectName: 'company',
      targetFieldName: 'opportunities',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'companyId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  installateur: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'installateur',
      label: i18nLabel(msg`Installateur`),
      description: i18nLabel(msg`Installateur lié au dossier`),
      icon: 'IconBuildingFactory2',
      isNullable: true,
      targetObjectName: 'installateur',
      targetFieldName: 'dossiers',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'installateurId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  taskTargets: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'taskTargets',
      label: i18nLabel(msg`Tasks`),
      description: i18nLabel(msg`Tasks tied to the opportunity`),
      icon: 'IconCheckbox',
      isUIReadOnly: true,
      isNullable: true,
      targetObjectName: 'taskTarget',
      targetFieldName: 'targetOpportunity',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  noteTargets: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'noteTargets',
      label: i18nLabel(msg`Notes`),
      description: i18nLabel(msg`Notes tied to the opportunity`),
      icon: 'IconNotes',
      isUIReadOnly: true,
      isNullable: true,
      targetObjectName: 'noteTarget',
      targetFieldName: 'targetOpportunity',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  attachments: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'attachments',
      label: i18nLabel(msg`Attachments`),
      description: i18nLabel(msg`Attachments linked to the opportunity`),
      icon: 'IconFileImport',
      isNullable: true,
      targetObjectName: 'attachment',
      targetFieldName: 'targetOpportunity',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  timelineActivities: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'timelineActivities',
      label: i18nLabel(msg`Timeline Activities`),
      description: i18nLabel(
        msg`Timeline Activities linked to the opportunity.`,
      ),
      icon: 'IconTimelineEvent',
      isNullable: true,
      targetObjectName: 'timelineActivity',
      targetFieldName: 'targetOpportunity',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  owner: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'owner',
      label: i18nLabel(msg`Owner`),
      description: i18nLabel(msg`Opportunity owner`),
      icon: 'IconUserCircle',
      isNullable: true,
      targetObjectName: 'workspaceMember',
      targetFieldName: 'ownedOpportunities',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'ownerId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // ENR - Informations dossier
  referenceDossierEnr: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'referenceDossierEnr',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Référence dossier ENR`),
      description: i18nLabel(msg`Référence unique du dossier ENR`),
      icon: 'IconHash',
      isNullable: true,
      isSearchable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  natureTravaux: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'natureTravaux',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Nature des travaux`),
      description: i18nLabel(msg`Nature des travaux ENR`),
      icon: 'IconTool',
      isNullable: true,
      options: [
        {
          id: '30303030-0004-4001-8001-000000000001',
          value: 'PAC_SEUL',
          label: i18nLabel(msg`PAC seul`),
          position: 0,
          color: 'blue',
        },
        {
          id: '30303030-0004-4001-8001-000000000002',
          value: 'PAC_SSC',
          label: i18nLabel(msg`PAC + SSC`),
          position: 1,
          color: 'blue',
        },
        {
          id: '30303030-0004-4001-8001-000000000003',
          value: 'PAC_BTD',
          label: i18nLabel(msg`PAC + BTD`),
          position: 2,
          color: 'blue',
        },
        {
          id: '30303030-0004-4001-8001-000000000004',
          value: 'PAC_BE',
          label: i18nLabel(msg`PAC + BE`),
          position: 3,
          color: 'blue',
        },
        {
          id: '30303030-0004-4001-8001-000000000005',
          value: 'PAC_BS',
          label: i18nLabel(msg`PAC + BS`),
          position: 4,
          color: 'blue',
        },
        {
          id: '30303030-0004-4001-8001-000000000006',
          value: 'PAC_SSC_PAG',
          label: i18nLabel(msg`PAC + SSC + PAG`),
          position: 5,
          color: 'blue',
        },
        {
          id: '30303030-0004-4001-8001-000000000007',
          value: 'PAC_SSC_VMC',
          label: i18nLabel(msg`PAC + SSC + VMC`),
          position: 6,
          color: 'blue',
        },
        {
          id: '30303030-0004-4001-8001-000000000008',
          value: 'CHAUDIERE_GRANULES',
          label: i18nLabel(msg`Chaudière à granulés`),
          position: 7,
          color: 'orange',
        },
        {
          id: '30303030-0004-4001-8001-000000000009',
          value: 'SSC_SEUL',
          label: i18nLabel(msg`SSC seul`),
          position: 8,
          color: 'turquoise',
        },
        {
          id: '30303030-0004-4001-8001-000000000010',
          value: 'PV',
          label: i18nLabel(msg`Panneaux photovoltaïque`),
          position: 9,
          color: 'yellow',
        },
        {
          id: '30303030-0004-4001-8001-000000000011',
          value: 'ISO_INT',
          label: i18nLabel(msg`Isolation intérieur`),
          position: 10,
          color: 'green',
        },
        {
          id: '30303030-0004-4001-8001-000000000012',
          value: 'ISO_EXT',
          label: i18nLabel(msg`Isolation extérieur`),
          position: 11,
          color: 'green',
        },
        {
          id: '30303030-0004-4001-8001-000000000013',
          value: 'RENOVATION_GLOBALE',
          label: i18nLabel(msg`Rénovation globale`),
          position: 12,
          color: 'purple',
        },
        {
          id: '30303030-0004-4001-8001-000000000014',
          value: 'RENOVATION_AMPLEUR',
          label: i18nLabel(msg`Rénovation d'ampleur`),
          position: 13,
          color: 'purple',
        },
        {
          id: '30303030-0004-4001-8001-000000000015',
          value: 'THERMOSTAT',
          label: i18nLabel(msg`Thermostat`),
          position: 14,
          color: 'gray',
        },
        {
          id: '30303030-0004-4001-8001-000000000016',
          value: 'LED',
          label: i18nLabel(msg`LED`),
          position: 15,
          color: 'yellow',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  couleurMpr: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'couleurMpr',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Couleur MPR`),
      description: i18nLabel(msg`Couleur Ma Prime Rénov du ménage`),
      icon: 'IconPalette',
      isNullable: true,
      options: [
        {
          id: '30303030-0005-4001-8001-000000000001',
          value: 'BLEU',
          label: i18nLabel(msg`Bleu`),
          position: 0,
          color: 'blue',
        },
        {
          id: '30303030-0005-4001-8001-000000000002',
          value: 'JAUNE',
          label: i18nLabel(msg`Jaune`),
          position: 1,
          color: 'yellow',
        },
        {
          id: '30303030-0005-4001-8001-000000000003',
          value: 'VIOLET',
          label: i18nLabel(msg`Violet`),
          position: 2,
          color: 'purple',
        },
        {
          id: '30303030-0005-4001-8001-000000000004',
          value: 'ROSE',
          label: i18nLabel(msg`Rose`),
          position: 3,
          color: 'red',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  statutDevis: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'statutDevis',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Statut devis`),
      description: i18nLabel(msg`Statut du devis`),
      icon: 'IconFileText',
      isNullable: true,
      options: [
        {
          id: '30303030-0006-4001-8001-000000000001',
          value: 'FACULTATIF',
          label: i18nLabel(msg`Facultatif`),
          position: 0,
          color: 'gray',
        },
        {
          id: '30303030-0006-4001-8001-000000000002',
          value: 'ATTENTE_DEVIS',
          label: i18nLabel(msg`Attente devis`),
          position: 1,
          color: 'yellow',
        },
        {
          id: '30303030-0006-4001-8001-000000000003',
          value: 'DEVIS_ENVOYE',
          label: i18nLabel(msg`Devis envoyé`),
          position: 2,
          color: 'blue',
        },
        {
          id: '30303030-0006-4001-8001-000000000004',
          value: 'DEVIS_A_CORRIGER',
          label: i18nLabel(msg`Devis à corriger`),
          position: 3,
          color: 'orange',
        },
        {
          id: '30303030-0006-4001-8001-000000000005',
          value: 'DEVIS_SIGNE',
          label: i18nLabel(msg`Devis signé`),
          position: 4,
          color: 'green',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  statutVisiteTechnique: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'statutVisiteTechnique',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Statut visite technique`),
      description: i18nLabel(msg`Statut de la visite technique`),
      icon: 'IconCalendarCheck',
      isNullable: true,
      options: [
        {
          id: '30303030-0007-4001-8001-000000000001',
          value: 'NON_OBLIGATOIRE',
          label: i18nLabel(msg`Non obligatoire`),
          position: 0,
          color: 'gray',
        },
        {
          id: '30303030-0007-4001-8001-000000000002',
          value: 'A_PLANIFIER',
          label: i18nLabel(msg`À planifier`),
          position: 1,
          color: 'yellow',
        },
        {
          id: '30303030-0007-4001-8001-000000000003',
          value: 'PLANIFIE',
          label: i18nLabel(msg`Planifié`),
          position: 2,
          color: 'blue',
        },
        {
          id: '30303030-0007-4001-8001-000000000004',
          value: 'REALISEE',
          label: i18nLabel(msg`Réalisée`),
          position: 3,
          color: 'green',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  statutFinancierMpr: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'statutFinancierMpr',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Statut financier MPR`),
      description: i18nLabel(msg`Statut financier Ma Prime Rénov`),
      icon: 'IconCoin',
      isNullable: true,
      options: [
        {
          id: '30303030-0008-4001-8001-000000000001',
          value: 'A_FACTURER',
          label: i18nLabel(msg`À facturer`),
          position: 0,
          color: 'yellow',
        },
        {
          id: '30303030-0008-4001-8001-000000000002',
          value: 'FACTURE',
          label: i18nLabel(msg`Facturé`),
          position: 1,
          color: 'blue',
        },
        {
          id: '30303030-0008-4001-8001-000000000003',
          value: 'PAYE_PARTIELLE',
          label: i18nLabel(msg`Payé partielle`),
          position: 2,
          color: 'orange',
        },
        {
          id: '30303030-0008-4001-8001-000000000004',
          value: 'PAYE_TOTAL',
          label: i18nLabel(msg`Payé total`),
          position: 3,
          color: 'green',
        },
        {
          id: '30303030-0008-4001-8001-000000000005',
          value: 'LITIGE',
          label: i18nLabel(msg`Litige`),
          position: 4,
          color: 'red',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  statutFinancierCee: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'statutFinancierCee',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Statut financier CEE`),
      description: i18nLabel(msg`Statut financier Certificats d'Économies d'Énergie`),
      icon: 'IconCoin',
      isNullable: true,
      options: [
        {
          id: '30303030-0009-4001-8001-000000000001',
          value: 'A_FACTURER',
          label: i18nLabel(msg`À facturer`),
          position: 0,
          color: 'yellow',
        },
        {
          id: '30303030-0009-4001-8001-000000000002',
          value: 'FACTURE',
          label: i18nLabel(msg`Facturé`),
          position: 1,
          color: 'blue',
        },
        {
          id: '30303030-0009-4001-8001-000000000003',
          value: 'PAYE_PARTIELLE',
          label: i18nLabel(msg`Payé partielle`),
          position: 2,
          color: 'orange',
        },
        {
          id: '30303030-0009-4001-8001-000000000004',
          value: 'PAYE_TOTAL',
          label: i18nLabel(msg`Payé total`),
          position: 3,
          color: 'green',
        },
        {
          id: '30303030-0009-4001-8001-000000000005',
          value: 'LITIGE',
          label: i18nLabel(msg`Litige`),
          position: 4,
          color: 'red',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  sourceDossier: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'sourceDossier',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Source du dossier`),
      description: i18nLabel(msg`Origine du dossier ENR`),
      icon: 'IconSourceCode',
      isNullable: true,
      options: [
        {
          id: '30303030-0010-4001-8001-000000000001',
          value: 'BASE_RDV_NON_ABOUTI',
          label: i18nLabel(msg`Base de RDV non abouti`),
          position: 0,
          color: 'gray',
        },
        {
          id: '30303030-0010-4001-8001-000000000002',
          value: 'BASE_DOSSIER_ANNULE',
          label: i18nLabel(msg`Base de dossier annulé`),
          position: 1,
          color: 'gray',
        },
        {
          id: '30303030-0010-4001-8001-000000000003',
          value: 'ACHAT_LEAD',
          label: i18nLabel(msg`Achat lead`),
          position: 2,
          color: 'blue',
        },
        {
          id: '30303030-0010-4001-8001-000000000004',
          value: 'ACHAT_LEAD_DATA',
          label: i18nLabel(msg`Achat lead data`),
          position: 3,
          color: 'purple',
        },
        {
          id: '30303030-0010-4001-8001-000000000005',
          value: 'AUTRES',
          label: i18nLabel(msg`Autres`),
          position: 4,
          color: 'gray',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  prioriteDossier: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'prioriteDossier',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Priorité dossier`),
      description: i18nLabel(msg`Niveau de priorité du dossier`),
      icon: 'IconFlag',
      isNullable: true,
      options: [
        {
          id: '30303030-0011-4001-8001-000000000001',
          value: 'HAUTE',
          label: i18nLabel(msg`Haute`),
          position: 0,
          color: 'red',
        },
        {
          id: '30303030-0011-4001-8001-000000000002',
          value: 'MOYENNE',
          label: i18nLabel(msg`Moyenne`),
          position: 1,
          color: 'yellow',
        },
        {
          id: '30303030-0011-4001-8001-000000000003',
          value: 'BASSE',
          label: i18nLabel(msg`Basse`),
          position: 2,
          color: 'green',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  financementPrincipal: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'financementPrincipal',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Financement principal`),
      description: i18nLabel(msg`Mode de financement principal du dossier`),
      icon: 'IconBuildingBank',
      isNullable: true,
      options: [
        {
          id: '30303030-0012-4001-8001-000000000001',
          value: 'MA_PRIME_RENOV',
          label: i18nLabel(msg`Ma Prime Rénov`),
          position: 0,
          color: 'green',
        },
        {
          id: '30303030-0012-4001-8001-000000000002',
          value: 'CEE',
          label: i18nLabel(msg`CEE`),
          position: 1,
          color: 'blue',
        },
        {
          id: '30303030-0012-4001-8001-000000000003',
          value: 'ECO_PTZ',
          label: i18nLabel(msg`Éco-PTZ`),
          position: 2,
          color: 'turquoise',
        },
        {
          id: '30303030-0012-4001-8001-000000000004',
          value: 'FONDS_PROPRES',
          label: i18nLabel(msg`Fonds propres`),
          position: 3,
          color: 'gray',
        },
        {
          id: '30303030-0012-4001-8001-000000000005',
          value: 'MPR_CEE',
          label: i18nLabel(msg`MPR + CEE`),
          position: 4,
          color: 'purple',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  typeBien: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'typeBien',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Type de bien`),
      description: i18nLabel(msg`Type de bien immobilier`),
      icon: 'IconHome',
      isNullable: true,
      options: [
        {
          id: '30303030-0013-4001-8001-000000000001',
          value: 'MAISON',
          label: i18nLabel(msg`Maison`),
          position: 0,
          color: 'orange',
        },
        {
          id: '30303030-0013-4001-8001-000000000002',
          value: 'APPARTEMENT',
          label: i18nLabel(msg`Appartement`),
          position: 1,
          color: 'blue',
        },
        {
          id: '30303030-0013-4001-8001-000000000003',
          value: 'IMMEUBLE',
          label: i18nLabel(msg`Immeuble`),
          position: 2,
          color: 'gray',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  usageBien: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'usageBien',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Usage du bien`),
      description: i18nLabel(msg`Usage du bien immobilier`),
      icon: 'IconHomeHeart',
      isNullable: true,
      options: [
        {
          id: '30303030-0014-4001-8001-000000000001',
          value: 'RESIDENCE_PRINCIPALE',
          label: i18nLabel(msg`Résidence principale`),
          position: 0,
          color: 'green',
        },
        {
          id: '30303030-0014-4001-8001-000000000002',
          value: 'RESIDENCE_SECONDAIRE',
          label: i18nLabel(msg`Résidence secondaire`),
          position: 1,
          color: 'blue',
        },
        {
          id: '30303030-0014-4001-8001-000000000003',
          value: 'LOCATIF',
          label: i18nLabel(msg`Locatif`),
          position: 2,
          color: 'yellow',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  dateContratEnr: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'dateContratEnr',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Date contrat ENR`),
      description: i18nLabel(msg`Date de signature du contrat ENR`),
      icon: 'IconCalendarCheck',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // ENR - Logement
  surfaceHabitable: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'surfaceHabitable',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Surface habitable`),
      description: i18nLabel(msg`Surface habitable en m²`),
      icon: 'IconRuler',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  nombreOccupants: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'nombreOccupants',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Nombre d'occupants`),
      description: i18nLabel(msg`Nombre d'occupants du logement`),
      icon: 'IconUsers',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  anneeConstruction: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'anneeConstruction',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Année de construction`),
      description: i18nLabel(msg`Année de construction du bien`),
      icon: 'IconCalendarStats',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  chauffageActuel: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'chauffageActuel',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Chauffage actuel`),
      description: i18nLabel(msg`Type de chauffage actuel du logement`),
      icon: 'IconFlame',
      isNullable: true,
      options: [
        {
          id: '30303030-0015-4001-8001-000000000001',
          value: 'ELECTRIQUE',
          label: i18nLabel(msg`Électrique`),
          position: 0,
          color: 'yellow',
        },
        {
          id: '30303030-0015-4001-8001-000000000002',
          value: 'GAZ',
          label: i18nLabel(msg`Gaz`),
          position: 1,
          color: 'blue',
        },
        {
          id: '30303030-0015-4001-8001-000000000003',
          value: 'FIOUL',
          label: i18nLabel(msg`Fioul`),
          position: 2,
          color: 'orange',
        },
        {
          id: '30303030-0015-4001-8001-000000000004',
          value: 'BOIS',
          label: i18nLabel(msg`Bois`),
          position: 3,
          color: 'orange',
        },
        {
          id: '30303030-0015-4001-8001-000000000005',
          value: 'PAC',
          label: i18nLabel(msg`Pompe à chaleur`),
          position: 4,
          color: 'turquoise',
        },
        {
          id: '30303030-0015-4001-8001-000000000006',
          value: 'AUTRE',
          label: i18nLabel(msg`Autre`),
          position: 5,
          color: 'gray',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  classeEnergieDpe: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'classeEnergieDpe',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Classe énergie DPE`),
      description: i18nLabel(msg`Classe énergétique du diagnostic de performance énergétique`),
      icon: 'IconLeaf',
      isNullable: true,
      options: [
        {
          id: '30303030-0016-4001-8001-000000000001',
          value: 'A',
          label: i18nLabel(msg`A`),
          position: 0,
          color: 'green',
        },
        {
          id: '30303030-0016-4001-8001-000000000002',
          value: 'B',
          label: i18nLabel(msg`B`),
          position: 1,
          color: 'green',
        },
        {
          id: '30303030-0016-4001-8001-000000000003',
          value: 'C',
          label: i18nLabel(msg`C`),
          position: 2,
          color: 'yellow',
        },
        {
          id: '30303030-0016-4001-8001-000000000004',
          value: 'D',
          label: i18nLabel(msg`D`),
          position: 3,
          color: 'orange',
        },
        {
          id: '30303030-0016-4001-8001-000000000005',
          value: 'E',
          label: i18nLabel(msg`E`),
          position: 4,
          color: 'orange',
        },
        {
          id: '30303030-0016-4001-8001-000000000006',
          value: 'F',
          label: i18nLabel(msg`F`),
          position: 5,
          color: 'red',
        },
        {
          id: '30303030-0016-4001-8001-000000000007',
          value: 'G',
          label: i18nLabel(msg`G`),
          position: 6,
          color: 'red',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  adresseBien: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'adresseBien',
      type: FieldMetadataType.ADDRESS,
      label: i18nLabel(msg`Adresse du bien`),
      description: i18nLabel(msg`Adresse du bien immobilier concerné`),
      icon: 'IconMap',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // ENR - Documents
  avisDimposition: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'avisDimposition',
      type: FieldMetadataType.LINKS,
      label: i18nLabel(msg`Avis d'imposition`),
      description: i18nLabel(msg`Avis d'imposition du ménage`),
      icon: 'IconFileDescription',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  taxeFonciere: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'taxeFonciere',
      type: FieldMetadataType.LINKS,
      label: i18nLabel(msg`Taxe foncière`),
      description: i18nLabel(msg`Document taxe foncière`),
      icon: 'IconFileDescription',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  cniRectoVerso: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'cniRectoVerso',
      type: FieldMetadataType.LINKS,
      label: i18nLabel(msg`CNI recto/verso`),
      description: i18nLabel(msg`Carte nationale d'identité recto/verso`),
      icon: 'IconId',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  justificatifDomicile: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'justificatifDomicile',
      type: FieldMetadataType.LINKS,
      label: i18nLabel(msg`Justificatif de domicile`),
      description: i18nLabel(msg`Justificatif de domicile du ménage`),
      icon: 'IconHome',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  acteNotarie: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'acteNotarie',
      type: FieldMetadataType.LINKS,
      label: i18nLabel(msg`Acte notarié`),
      description: i18nLabel(msg`Acte notarié de propriété`),
      icon: 'IconFileText',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  photosEnr: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'photosEnr',
      type: FieldMetadataType.LINKS,
      label: i18nLabel(msg`Photos ENR`),
      description: i18nLabel(msg`Photos de l'installation ENR`),
      icon: 'IconPhoto',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  autresDocuments: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'autresDocuments',
      type: FieldMetadataType.LINKS,
      label: i18nLabel(msg`Autres documents`),
      description: i18nLabel(msg`Autres documents du dossier`),
      icon: 'IconFiles',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // ENR - Installation
  dateDebutTravaux: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'dateDebutTravaux',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Date début travaux`),
      description: i18nLabel(msg`Date de début des travaux`),
      icon: 'IconCalendarPlus',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  dateFinTravaux: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'dateFinTravaux',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Date fin travaux`),
      description: i18nLabel(msg`Date de fin des travaux`),
      icon: 'IconCalendarCheck',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  notesInstallation: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'notesInstallation',
      type: FieldMetadataType.RICH_TEXT,
      label: i18nLabel(msg`Notes installation`),
      description: i18nLabel(msg`Notes relatives à l'installation`),
      icon: 'IconNotes',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // ENR - Suivi financier
  montantAideMpr: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'montantAideMpr',
      type: FieldMetadataType.CURRENCY,
      label: i18nLabel(msg`Montant aide MPR`),
      description: i18nLabel(msg`Montant de l'aide Ma Prime Rénov`),
      icon: 'IconCurrencyEuro',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  montantAideCee: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'montantAideCee',
      type: FieldMetadataType.CURRENCY,
      label: i18nLabel(msg`Montant aide CEE`),
      description: i18nLabel(msg`Montant de l'aide CEE`),
      icon: 'IconCurrencyEuro',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  montantCommission: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'montantCommission',
      type: FieldMetadataType.CURRENCY,
      label: i18nLabel(msg`Montant commission`),
      description: i18nLabel(msg`Montant de la commission`),
      icon: 'IconCurrencyEuro',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  resteAChargeClient: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'resteAChargeClient',
      type: FieldMetadataType.CURRENCY,
      label: i18nLabel(msg`Reste à charge client`),
      description: i18nLabel(msg`Montant restant à charge du client`),
      icon: 'IconCurrencyEuro',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  totalAidePercu: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'totalAidePercu',
      type: FieldMetadataType.CURRENCY,
      label: i18nLabel(msg`Total aide perçu`),
      description: i18nLabel(msg`Total des aides perçues`),
      icon: 'IconCurrencyEuro',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  montantTotalFacture: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'montantTotalFacture',
      type: FieldMetadataType.CURRENCY,
      label: i18nLabel(msg`Montant total facturé`),
      description: i18nLabel(msg`Montant total de la facture`),
      icon: 'IconCurrencyEuro',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // ENR - Administratif ANAH
  dateDepotAnah: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'dateDepotAnah',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Date dépôt ANAH`),
      description: i18nLabel(msg`Date de dépôt du dossier ANAH`),
      icon: 'IconCalendarPlus',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  dateAccordAnah: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'dateAccordAnah',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Date accord ANAH`),
      description: i18nLabel(msg`Date d'accord de l'ANAH`),
      icon: 'IconCalendarCheck',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  numeroDossierAnah: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'numeroDossierAnah',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Numéro dossier ANAH`),
      description: i18nLabel(msg`Numéro de référence du dossier ANAH`),
      icon: 'IconHash',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
