apiVersion: v1
kind: PersistentVolume
metadata:
  name: orrtyl-crm-server-pv
  namespace: orrtyl-crm
spec:
  storageClassName: default
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
