apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orrtyl-crm-server-pvc
  namespace: orrtyl-crm
spec:
  storageClassName: default
  volumeName: orrtyl-crm-server-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
