apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orrtyl-crm-docker-data-pvc
  namespace: orrtyl-crm
spec:
  storageClassName: default
  volumeName: orrtyl-crm-docker-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
