apiVersion: v1
kind: Service
metadata:
  name: orrtyl-crm-server
  namespace: orrtyl-crm
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: http-tcp
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: orrtyl-crm-server
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
