version: "3.8"

services:
  db:
    container_name: orrtyl-db
    image: postgres:16
    environment:
      POSTGRES_DB: orrtyl_energie
      POSTGRES_USER: orrtyl_app_user
      POSTGRES_PASSWORD: ${PG_DATABASE_PASSWORD}
    volumes:
      - orrtyl-db-data:/var/lib/postgresql/data:Z

  redis:
    container_name: orrtyl-redis
    image: redis:latest
    command: ["--maxmemory-policy", "noeviction"]
    volumes:
      - orrtyl-redis-data:/data:Z

  server:
    container_name: orrtyl-server
    image: orrtyl/twenty:latest
    environment:
      NODE_PORT: "3000"
      SERVER_URL: ${SERVER_URL}
      PG_DATABASE_URL: "postgresql://orrtyl_app_user:${PG_DATABASE_PASSWORD}@orrtyl-db:5432/orrtyl_energie"
      REDIS_URL: "redis://orrtyl-redis:6379"
      APP_SECRET: ${APP_SECRET}
      NODE_ENV: production
      LOG_LEVEL: info
    volumes:
      - orrtyl-server-data:/app/docker-data:Z
    ports:
      - 127.0.0.1:8080:3000

  worker:
    container_name: orrtyl-worker
    image: orrtyl/twenty:latest
    command: yarn worker:prod
    environment:
      SERVER_URL: ${SERVER_URL}
      PG_DATABASE_URL: "postgresql://orrtyl_app_user:${PG_DATABASE_PASSWORD}@orrtyl-db:5432/orrtyl_energie"
      REDIS_URL: "redis://orrtyl-redis:6379"
      APP_SECRET: ${APP_SECRET}
      DISABLE_DB_MIGRATIONS: "true"
      NODE_ENV: production
      LOG_LEVEL: info
    volumes:
      - orrtyl-server-data:/app/docker-data:Z
    init: true

volumes:
  orrtyl-db-data:
  orrtyl-server-data:
  orrtyl-redis-data:
